baseurl = "http://www.tigrou.nl"
languageCode = "en-us"
title = "Rob's blog"
paginate = 9 # To specify a multiple of 3
theme="material-design"
copyright = "© 2015 Copyright Rob Sonke"



MetaDataFormat = "toml"

[author]
    name = "Rob Sonke"

[permalinks]
    # Optional. Change the permalink format for the 'post' content type.
    # The format shown here is the same one Jekyll/Octopress uses by default.
    post = "/:year/:month/:day/:title/"

[indexes]
    # Optional. Use if you want tags and lists.
    category = "categories"

#
# All parameters below here are optional and can be mixed and matched.
#
[params]
    description = "Personal blog of Rob Sonke, mostly about any kind of software development"

    headerCover = "header2.jpg"
    googleAnalyticsUserID = "UA-7307813-1"

    github = "robsonke"
    linkedin = "robsonke"
    facebook = "rob.sonke"
    twitter = "rsonke"


